DELETE http://localhost:3001/api/blogs/6662d52187bb3281b57488b2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NjRkZmQyYWZmNzVhNTZiOGM2OTAwYTciLCJpYXQiOjE3MTc2Njc5NzF9.fv_z41I06hu_Ddu3ybMv0wIBR1lqy_dlMRxR0_3QNzk
